name: Observation.org Blog
favicon: null
layout_spectrum: 0.14657418266870081
typography_spectrum: 0.5949762756936252
title: Observation.org Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3621020659338683
  lightness: 0.6655822414904833
  saturation: 0.382975363638252
  rhythmicContrast: 0.04364658356644213
purpose: []
